### ISSUE TITLE
Question about performance

### ISSUE THREAD

**Issue by fabiuz7** [PowerBroker2/DFPlayerMini_Fast#38]
Hi @PowerBroker2 , 
thank you for your work. I would ask which optimization you had applied to improve execution speed, as claimed in the description. Just curiosity :) About simplicity I have no doubt, it is clearer than others.

**Comment by PowerBroker2** [comment]
This library is faster than the original since the original has a 8ms or so hard-coded delay for every command (and possibly a longer one for queries). This delay is not hard-coded in this lib. Are you having issues with processing speed?

**Comment by fabiuz7** [comment]
Actually I have a project that uses the original library, but I never did test on performance neither looked into the library.
I have just discovered your library, I was wondering a migration to your solution.

Are those hardcoded delays useful to something? I had already meet other libraries making use of "casual" delays...

**Comment by PowerBroker2** [comment]
> Are those hardcoded delays useful to something?

It really depends. The original lib uses the delay to keep the user from spamming commands/queries (otherwise the DFPlayer will become unresponsive), but this is only an edge case and such delays can be manually handled in the sketch if really needed.

Personally, I think my lib performs much better than the original as long as you know its limitations and how to use it.

**Comment by fabiuz7** [comment]
Perfect, thanks for the clear answer. Maybe you could add a similar explanation in the readme, so new comers will immediately understand the major improvements
